import os
import sys
import csv
import json
import pandas as pd
import argparse as ap
from pathlib import Path



# Get the absolute path of the current file
current_file_path = os.path.abspath(__file__)
# Get the parent directory of the current file
project_root = os.path.dirname(os.path.dirname(current_file_path))
sys.path.append(project_root)
# scripts/ 目录, 保证从任意工作目录运行时都能 import utils
sys.path.insert(0, os.path.dirname(current_file_path))
from utils.GA import LeverageSyner_GA_codesize_file, LeverageSyner_GA_codesize_project
from utils.common import get_inst_count_method, check_dataset_arch_matches_opt

parser = ap.ArgumentParser()
parser.add_argument("--dataset", type=str, required=True, help="the directory containing .ll files or specific .ll files to be tuned")
parser.add_argument("--llvm_tools_path", type=str, required=True, help="Path to a specific version LLVM binary files")
parser.add_argument("--paircsv", type=str, required=True, help="the synergistic pair list to be used for training")
parser.add_argument("--opt-level", type=str, default="Oz", choices=["O0", "O1", "O2", "O3", "Os", "Oz"], help="optimization level for the GA baseline scoring (default: Oz)")
parser.add_argument("--count_mode", type=str, default="auto", choices=["auto", "opt-stats", "text", "obj-size"], help="instruction counting mode for scoring (default: auto)")
parser.add_argument("--search_scope", type=str, default="file", choices=["file", "project"], help="search scope of the optimal pass sequence: file (per-file, default) or project (one common sequence for all files)")
parser.add_argument("--max-path-length", type=int, default=2, help="maximum length of initial GA sequences in number of passes (default: 2)")
parser.add_argument("--baseline_manifest", type=str, default=None, help="C-input baseline manifest JSON (generated by ruyituner.py): maps each .ll to its original .c/.i source so that, under obj-size counting, the baseline is measured by compiling the source directly with clang -O<level> -c")
parser.add_argument("--project_name", type=str, default=None, help="project name used to name the Step3 pass-list CSV in project mode (default: derived from the dataset directory)")
parser.add_argument("--output_dir", type=str, default=None, help="directory for the Step3 pass-list CSV in project mode (default: <项目根目录>/output)")

args = parser.parse_args()

print("计数方式:", get_inst_count_method(args.llvm_tools_path, count_mode=args.count_mode))

# C 输入基线清单: 由 ruyituner.py 在 C→IR 编译时生成, 映射 .ll 相对路径 ->
# 原始 .c/.i 源文件; obj-size 计数方式下基线直接用 clang -O<level> -c 编译
# 源码统计 .o, 更贴近真实编译; 清单缺失/读取失败或非 obj-size 模式时保持
# 原有 IR 口径基线
baseline_map = {}
if args.baseline_manifest:
    manifest = None
    try:
        with open(args.baseline_manifest, 'r', encoding='utf-8') as mf:
            manifest = json.load(mf)
    except (OSError, ValueError) as e:
        print(f"警告: 无法读取基线清单 {args.baseline_manifest}: {e}; 基线回退 IR 口径.")
    if manifest:
        src_root = manifest.get('src_root') or ''
        for rel, src in (manifest.get('files') or {}).items():
            baseline_map[rel] = {
                'src': src,
                'src_root': src_root,
                'c_std': manifest.get('c_std'),
                'c_flags': manifest.get('c_flags'),
            }
        if args.count_mode == 'obj-size':
            print(f"C 输入基线: clang -{args.opt_level} -c 直接编译源码生成 .o 统计 (共 {len(baseline_map)} 个源文件).")
        else:
            print(f"注意: clang 直接编译基线仅在 --count_mode obj-size 下生效, 当前 {args.count_mode} 模式基线仍按 IR 口径统计.")


def _baseline_src_of(filename):
    '''按数据集目录下的相对路径查 C 输入基线清单, 未命中返回 None.'''
    rel = os.path.relpath(os.path.abspath(str(filename)), os.path.abspath(args.dataset))
    return baseline_map.get(rel)


def _default_project_name():
    '''项目名默认取数据集目录(或单文件所在目录)的名称.'''
    d = os.path.abspath(args.dataset)
    if os.path.isfile(d):
        d = os.path.dirname(d)
    return os.path.basename(os.path.normpath(d)) or 'dataset'


def write_project_passlist(path, project_name, output_dir):
    '''把项目模式找到的最优 pass 序列写入 output_dir/Step3_<项目名>_PassList.csv.

    每行一个 pass, 保持序列顺序 (可直接逗号连接后用于实际编译);
    序列为空 (无收益) 时不写文件, 只提示.'''
    if not path:
        print('最优序列为空, 不写出 Step3 Pass 列表.')
        return
    os.makedirs(output_dir, exist_ok=True)
    out_path = os.path.join(output_dir, f'Step3_{project_name}_PassList.csv')
    with open(out_path, 'w', encoding='utf-8', newline='') as fh:
        writer = csv.writer(fh)
        writer.writerow(['pass'])
        for p in path:
            writer.writerow([p])
    print(f'Pass 列表已写入: {out_path}')


df = pd.read_csv(args.paircsv)
pairlist= df["synerpair"].tolist()
# 将列表中的元素由str转换为元组
pairlist = [eval(pair) for pair in pairlist]


if os.path.isdir(args.dataset):
    filenames = list(Path(args.dataset).rglob("*.ll"))
elif os.path.isfile(args.dataset) and args.dataset.endswith(".ll"):
    filenames = [args.dataset]
else:
    raise ValueError("The dataset argument must be a directory containing .ll files or a specific .ll file.")

# 校验数据集架构与 opt 默认目标一致, 避免用 x86 的 opt 处理 riscv 的 .ll 文件
check_dataset_arch_matches_opt([str(f) for f in filenames], os.path.join(args.llvm_tools_path, 'opt'))

if args.search_scope == 'project':
    # 项目模式: 为全部输入文件寻找一条公共的最优 pass 序列 (聚合适应度 GA)
    file_codes = []
    for filename in filenames:
        with open(filename, 'r') as ll_file:
            file_codes.append((str(filename), ll_file.read()))
    path, score, total_baseline, total_after = LeverageSyner_GA_codesize_project(
        pairlist, file_codes, llvm_tools_path=args.llvm_tools_path,
        opt_level=args.opt_level, count_mode=args.count_mode,
        max_path_length=args.max_path_length,
        baseline_srcs=[_baseline_src_of(f) for f in filenames])
    final_path = path if score != 0 else []
    out_dir_run = args.output_dir or os.path.join(project_root, 'output')
    project_name = args.project_name or _default_project_name()
    print("Path: ", final_path)
    print("Total Baseline Size: ", total_baseline)
    print("Total Optimized Size: ", total_after)
    print("Overall Reduction Rate: ", f"{score * 100:.2f}%")
    # 把最优 pass 序列写入 Step3_<项目名>_PassList.csv, 供实际编译对比阶段直接使用
    write_project_passlist(final_path, project_name, out_dir_run)
    # 基线/优化后大小/缩减率写入 Step3_<项目名>_Result.json, 供实际编译对比复用 (不重新计算)
    if final_path:
        result_path = os.path.join(out_dir_run, f'Step3_{project_name}_Result.json')
        with open(result_path, 'w', encoding='utf-8') as fh:
            json.dump({
                'project_name': project_name,
                'path': final_path,
                'total_baseline': int(total_baseline),
                'total_optimized': int(total_after),
                'overall_reduction_rate': score,
                'opt_level': args.opt_level,
                'count_mode': args.count_mode,
                'file_count': len(file_codes),
            }, fh, ensure_ascii=False, indent=2)
        print(f'结果已写入: {result_path}')
    print(f"Done: one common pass sequence for {len(file_codes)} files.")
    sys.exit(0)

# 汇总所有文件的基线大小与优化后大小, 整体平均缩减率 = (Σ基线 - Σ优化后) / Σ基线;
# 缩减率为0的文件同样计入分母, 会拉低整体平均缩减率
total_baseline = 0
total_after = 0

for i, filename in enumerate(filenames, start=1):

    with open(filename, 'r') as ll_file:
        ll_code = ll_file.read()
    print(f"Current File [{i}/{len(filenames)}]:", filename)  
    path, score, baseline_count, after_count = LeverageSyner_GA_codesize_file(pairlist, ll_code, llvm_tools_path=args.llvm_tools_path, opt_level=args.opt_level, count_mode=args.count_mode, max_path_length=args.max_path_length, baseline_src=_baseline_src_of(filename))
    # 0分文件也按统一格式输出, 0分时Path输出为空; 但0分文件同样计入整体平均缩减率的分母
    total_baseline += int(baseline_count)
    total_after += int(after_count)
    mean = (total_baseline - total_after) / total_baseline if total_baseline > 0 else 0.0
    print("Path: ", path if score != 0 else [])
    print(f"{args.opt_level} Baseline Size: {baseline_count}")
    print(f"RuyiTuner Optimized Size: {after_count}")
    print("Code Size Reduction Rate: ", f"{score * 100:.2f}%")
    print("Mean Reduction Rate: ", f"{mean * 100:.2f}%")
    print()

print(f"Done: {len(filenames)} files scored in total.")
# 汇总输出全部评分文件的优化前总大小、优化后总大小与整体缩减比例
overall = (total_baseline - total_after) / total_baseline if total_baseline > 0 else 0.0
print(f"Total Baseline Size: {total_baseline}")
print(f"Total Optimized Size: {total_after}")
print(f"Overall Reduction Rate: {overall * 100:.2f}%")

